---
title: Données Filosofi
author: etudiantp4
date: '2026-05-13'
slug: lib-rez-roubaix
categories: []
tags: []
---

Tout d’abord, intéressons-nous au niveau de vie basé sur les revenus pour observer les possibles différences entre les deux communes. Pour cela, nous utiliserons des données *filosofi de l'INSEE* nous permettant de comparer les revenus des ménages en combinant les données fiscales.

## Comparaison des revenus médian entre Lille et Roubaix

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(tidyverse)
library(ggplot2)

data_brute <- read_excel("filo.xlsx", sheet = 1, skip = 5)

donnees_propres <- data_brute %>%
  filter(COM %in% c("59350", "59512")) %>%
  mutate(DEC_MED21 = as.numeric(DEC_MED21)) %>%
  filter(!is.na(DEC_MED21))

ggplot(donnees_propres, aes(x = LIBCOM, y = DEC_MED21, fill = LIBCOM)) +
  geom_boxplot() +
  labs(title = "Niveau de vie médian par quartier",
       x = "Ville",
       y = "Revenu médian") +
  theme_minimal()
```

### L’analyse à travers le prisme des données Filosofi (INSEE) permet de mettre en lumière avant tout une différence notable de niveau de vie entre les deux communes mais aussi, une ségrégation spatiale majeure au sein de la métropole lilloise.

En observant ce graphique "Niveau de vie médian par quartier", on remarque déjà une nette différence avec Lille qui possède un niveau de vie par habitant plus élevé que celui de Roubaix. Seulement, on remarque aussi un écart assez prononcé pour la ville de Lille, ce qui indique une forte ségrégation spatiale entre les différents quartiers de la ville avec certains aisés (notamment le Vieux-Lille) ou d'autres plus pauvres (Moulins). L'écart est plus réduit à Roubaix, ce qui montre un écart de richesse moins prononcé mais un niveau de vie inférieur à la ville de Lille.

*<mark>Site réalisé par Mathis et Lucien Groupe 7</mark>*